chore: dependencies and logging
GemeenteNijmegen/irma-issue-app pull request #242
Opened 2023-05-08 09:14 UTC by marnixdessing

2023-05-08 09:39 UTC, joostvanderborg requested changes

2023-05-08 09:39 UTC, joostvanderborg commented on src/app/auth/handleRequest.ts
> +  console.debug('Creating session object...', cookies, dynamoDBClient);
gezien je hiermee session hijacking wel erg gemakkelijk maakt: kunnen we de cookies enigszins anonimiseren (keys + eerste paar karakters waarde of zo?)

2023-05-08 09:59 UTC, marnixdessing commented on src/app/auth/handleRequest.ts
> +  console.debug('Creating session object...', cookies, dynamoDBClient);
Hmm lastig. De cookie string is een semicolon separated string van cookies `<naam>=<value>;` format. Ik weet niet precies wat er fout gaat bij het maken van het session object. Maar er gaat iets dusdanig fout dat de hele runtime niet eens met een error faalt (de invalid_request dus). Wellicht kan ik eerst nog extra tests toevoegen aan het Session object.

2023-05-17 13:32 UTC, marnixdessing commented
Deze fix kan niet omdat we de cookie string anders loggen.

2023-05-17 13:32 UTC, closed without merging